# config/config.yaml
model:
  path: "models/yolov8n.pt"
  confidence_threshold: 0.5

animals:
  classes:
    - coco_id: 17
      name: "horse"
      color: [255, 0, 0]
    - coco_id: 18
      name: "sheep"
      color: [0, 255, 0]
    - coco_id: 19
      name: "cow"
      color: [0, 0, 255]
    - coco_id: 20
      name: "elephant"
      color: [255, 255, 0]
    - coco_id: 21
      name: "bear"
      color: [255, 0, 255]
    - coco_id: 22
      name: "zebra"
      color: [0, 255, 255]
    - coco_id: 23
      name: "giraffe"
      color: [255, 165, 0]

influxdb:
  url: "http://localhost:8086"
  token: "your-infulxdb-token"
  org: "zoo-monitoring"
  bucket: "animal-detection"

video:
  source: "path-to-your-video" # 0 for webcam, or path to video file
  save_output: true
  output_path: "output/detected_video.mp4"

dashboard:
  host: "localhost"
  port: 8501
  auto_refresh: 30  # seconds